<a href="https://colab.research.google.com/github/ethandsz/PyTorch/blob/main/Income_Happiness_Predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [122]:
import numpy as np
import torch

In [123]:
inputs = np.array([[3.86264741839841], [4.97938138246536],
                  [4.9239569362253],[3.21437243884429],
                  [7.19640925107524], [3.72964347945526],
                  [4.67451738892123], [4.49810382071882],
                  [3.12163052614778], [4.6399144353345]],
                  dtype = "float32")
targets = np.array([[2.31448898284741], [3.43348975853174],
                   [4.59937340433575], [2.79111380280692],
                    [5.59639827336202], [2.45855587216119],
                    [3.19299180946247],[1.90713683309599],
                    [2.94244987165905], [3.73794160485342]],
                   dtype = "float32")
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [12]:
from torch.utils.data import TensorDataset

In [124]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[3.8626],
         [4.9794],
         [4.9240]]), tensor([[2.3145],
         [3.4335],
         [4.5994]]))

In [125]:
from torch.utils.data import DataLoader

In [126]:
batch_size = 3
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [127]:
for xy, yx in train_dl:
  print(xy)
  print(yx)
  break

tensor([[7.1964],
        [3.7296],
        [4.9240]])
tensor([[5.5964],
        [2.4586],
        [4.5994]])


In [128]:
import torch.nn as nn

In [140]:
model = nn.Linear(1,1)
list(model.parameters())

[Parameter containing:
 tensor([[-0.6962]], requires_grad=True), Parameter containing:
 tensor([-0.4930], requires_grad=True)]

In [141]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[-3.1820],
        [-3.9594],
        [-3.9209],
        [-2.7307],
        [-5.5028],
        [-3.0894],
        [-3.7472],
        [-3.6244],
        [-2.6661],
        [-3.7231]], grad_fn=<AddmmBackward0>)
tensor([[2.3145],
        [3.4335],
        [4.5994],
        [2.7911],
        [5.5964],
        [2.4586],
        [3.1930],
        [1.9071],
        [2.9424],
        [3.7379]])


In [142]:
import torch.nn.functional as F

In [143]:
loss_func = F.mse_loss

In [144]:
loss = loss_func(preds,targets)
print(loss)


tensor(50.7812, grad_fn=<MseLossBackward0>)


In [145]:
print(loss.backward())

None


In [146]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [147]:
def train(epochs, model, loss_func, opt, train_dl):
  for epoch in range(epochs):
    for xy, yx in train_dl:
      preds = model(xy)
      loss = loss_func(preds,yx)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch % 10 == 0):
          print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch, epochs, loss.item()))


In [153]:
train(1000,model,loss_func,opt,train_dl)

Epoch [0/1000], Loss: 14.5173
Epoch [10/1000], Loss: 22.0635
Epoch [20/1000], Loss: 13.4511
Epoch [30/1000], Loss: 12.9517
Epoch [40/1000], Loss: 14.2163
Epoch [50/1000], Loss: 19.0200
Epoch [60/1000], Loss: 8.7742
Epoch [70/1000], Loss: 20.0649
Epoch [80/1000], Loss: 19.3243
Epoch [90/1000], Loss: 9.4955
Epoch [100/1000], Loss: 17.9465
Epoch [110/1000], Loss: 15.1829
Epoch [120/1000], Loss: 40.5460
Epoch [130/1000], Loss: 14.0566
Epoch [140/1000], Loss: 15.4083
Epoch [150/1000], Loss: 11.1312
Epoch [160/1000], Loss: 24.5003
Epoch [170/1000], Loss: 16.1664
Epoch [180/1000], Loss: 4.5186
Epoch [190/1000], Loss: 4.2523
Epoch [200/1000], Loss: 5.9750
Epoch [210/1000], Loss: 10.3544
Epoch [220/1000], Loss: 9.1718
Epoch [230/1000], Loss: 6.0027
Epoch [240/1000], Loss: 3.1514
Epoch [250/1000], Loss: 7.5534
Epoch [260/1000], Loss: 4.6333
Epoch [270/1000], Loss: 18.0563
Epoch [280/1000], Loss: 7.9651
Epoch [290/1000], Loss: 4.7635
Epoch [300/1000], Loss: 6.5543
Epoch [310/1000], Loss: 16.2063


In [154]:
preds = model(inputs)
preds

tensor([[2.1082],
        [2.7808],
        [2.7474],
        [1.7177],
        [4.1162],
        [2.0280],
        [2.5972],
        [2.4909],
        [1.6618],
        [2.5763]], grad_fn=<AddmmBackward0>)

In [155]:
targets

tensor([[2.3145],
        [3.4335],
        [4.5994],
        [2.7911],
        [5.5964],
        [2.4586],
        [3.1930],
        [1.9071],
        [2.9424],
        [3.7379]])

In [158]:
model(torch.tensor([[7.19640925107524]]))

tensor([[4.1162]], grad_fn=<AddmmBackward0>)