<a href="https://colab.research.google.com/github/ethandsz/PyTorch/blob/main/Income_Happiness_Predictions_With_importedDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving i - Sheet1.csv to i - Sheet1.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Income - Sheet1.csv to Income - Sheet1.csv


In [ ]:
inc = pd.read_csv('i - Sheet1.csv')
income = torch.tensor(inc.values, dtype = torch.float32)
hap = pd.read_csv('Happiness - Sheet1.csv')
happiness = torch.tensor(hap.values, dtype = torch.float32)
inputs = np.array([[3.86264741839841], [4.97938138246536],
                  [4.9239569362253],[3.21437243884429],
                  [7.19640925107524], [3.72964347945526],
                  [4.67451738892123], [4.49810382071882],
                  [3.12163052614778], [4.6399144353345]],
                  dtype = "float32")
targets = np.array([[2.31448898284741], [3.43348975853174],
                   [4.59937340433575], [2.79111380280692],
                    [5.59639827336202], [2.45855587216119],
                    [3.19299180946247],[1.90713683309599],
                    [2.94244987165905], [3.73794160485342]],
                   dtype = "float32")
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(happiness)

tensor([[2.3145],
        [3.4335],
        [4.5994],
        [2.7911],
        [5.5964],
        [2.4586],
        [3.1930],
        [1.9071],
        [2.9424],
        [3.7379],
        [3.1754],
        [2.0090],
        [5.9518],
        [5.9605],
        [1.4458],
        [2.8986],
        [1.2312],
        [2.3130],
        [2.6661],
        [2.5847],
        [5.7474],
        [2.5465],
        [1.2008],
        [3.0783],
        [4.3178],
        [5.3815],
        [3.5652],
        [0.9534],
        [2.1692],
        [2.0608],
        [6.2991],
        [1.5904],
        [2.2509],
        [5.9142],
        [2.1918],
        [5.7678],
        [0.9729],
        [5.0106],
        [2.2397],
        [1.9276],
        [3.3581],
        [2.4001],
        [3.4080],
        [2.5762],
        [2.4731],
        [3.7527],
        [4.0876],
        [3.5432],
        [5.3484],
        [3.0564],
        [1.5584],
        [3.2251],
        [5.0342],
        [3.8574],
        [3.6191],
        [4

In [ ]:
from torch.utils.data import TensorDataset

In [ ]:
train_ds = TensorDataset(income, happiness)
train_ds[0:3]

(tensor([[3.8626],
         [4.9794],
         [4.9240]]), tensor([[2.3145],
         [3.4335],
         [4.5994]]))

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [ ]:
for xy, yx in train_dl:
  print(xy)
  print(yx)
  break

tensor([[1.8245],
        [4.7557],
        [3.1540],
        [3.0355],
        [2.3814]])
tensor([[0.2660],
        [2.6661],
        [1.2941],
        [2.2604],
        [2.1763]])


In [ ]:
import torch.nn as nn

In [ ]:
model = nn.Linear(1,1)
list(model.parameters())

[Parameter containing:
 tensor([[-0.2941]], requires_grad=True), Parameter containing:
 tensor([0.1727], requires_grad=True)]

In [ ]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[-0.9635],
        [-1.2920],
        [-1.2757],
        [-0.7728],
        [-1.9441],
        [-0.9244],
        [-1.2023],
        [-1.1504],
        [-0.7455],
        [-1.1921]], grad_fn=<AddmmBackward0>)
tensor([[2.3145],
        [3.4335],
        [4.5994],
        [2.7911],
        [5.5964],
        [2.4586],
        [3.1930],
        [1.9071],
        [2.9424],
        [3.7379]])


In [ ]:
import torch.nn.functional as F

In [ ]:
loss_func = F.mse_loss

In [ ]:
loss = loss_func(preds,targets)
print(loss)


tensor(21.5169, grad_fn=<MseLossBackward0>)


In [ ]:
print(loss.backward())

None


In [ ]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [ ]:
def train(epochs, model, loss_func, opt, train_dl):
  for epoch in range(epochs):
    for xy, yx in train_dl:
      preds = model(xy)
      loss = loss_func(preds,yx)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch % 10 == 0):
          print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch, epochs, loss.item()))


In [ ]:
train(1000,model,loss_func,opt,train_dl)

Epoch [0/1000], Loss: 5.2043
Epoch [10/1000], Loss: 13.8072
Epoch [20/1000], Loss: 4.0792
Epoch [30/1000], Loss: 2.6832
Epoch [40/1000], Loss: 0.9252
Epoch [50/1000], Loss: 1.2320
Epoch [60/1000], Loss: 1.9877
Epoch [70/1000], Loss: 0.1440
Epoch [80/1000], Loss: 0.1288
Epoch [90/1000], Loss: 0.0315
Epoch [100/1000], Loss: 0.0772
Epoch [110/1000], Loss: 0.4968
Epoch [120/1000], Loss: 0.0423
Epoch [130/1000], Loss: 0.5958
Epoch [140/1000], Loss: 0.2089
Epoch [150/1000], Loss: 0.3666
Epoch [160/1000], Loss: 0.5934
Epoch [170/1000], Loss: 0.2149
Epoch [180/1000], Loss: 0.2009
Epoch [190/1000], Loss: 0.2601
Epoch [200/1000], Loss: 0.1499
Epoch [210/1000], Loss: 0.0979
Epoch [220/1000], Loss: 0.4111
Epoch [230/1000], Loss: 0.1094
Epoch [240/1000], Loss: 0.3743
Epoch [250/1000], Loss: 0.5402
Epoch [260/1000], Loss: 0.5238
Epoch [270/1000], Loss: 0.1271
Epoch [280/1000], Loss: 0.8284
Epoch [290/1000], Loss: 0.0257
Epoch [300/1000], Loss: 1.8955
Epoch [310/1000], Loss: 1.1653
Epoch [320/1000], 

In [ ]:
preds = model(inputs)
preds

tensor([[2.9919],
        [3.7621],
        [3.7239],
        [2.5449],
        [5.2910],
        [2.9002],
        [3.5518],
        [3.4302],
        [2.4809],
        [3.5280]], grad_fn=<AddmmBackward0>)

In [ ]:
targets

tensor([[2.3145],
        [3.4335],
        [4.5994],
        [2.7911],
        [5.5964],
        [2.4586],
        [3.1930],
        [1.9071],
        [2.9424],
        [3.7379]])

In [ ]:
model(torch.tensor([[7.11947859451175]]))

tensor([[5.2380]], grad_fn=<AddmmBackward0>)